name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create virtual environment
        run: |
          python -m venv env
          source env/bin/activate

      - name: Install dependencies
        run: |
          source env/bin/activate
          pip install --upgrade pip
          sudo apt-get install -y pylint
          pip install -r requirements.txt

      - name: Lint code with Pylint
        run: |
          source env/bin/activate
          pylint * || echo "Pylint found issues"
